name: intership_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Iconos estilo iOS
  cupertino_icons: ^1.0.8

  # --- LIBRERÍAS DE FIREBASE ---
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.0.0

  # Diseño y Tipografía
  google_fonts: ^6.2.1

  # Utilidades
  file_picker: ^8.0.0  
  url_launcher: ^6.3.0
  intl: ^0.20.2

  # --- NUEVO: MAPAS (OPENSTREETMAP) ---
  # Agregamos esto para usar mapas sin pagar y sin API Key
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/unimet_logo.png
    - assets/Logo_app.jpeg