name: intership_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Iconos estilo iOS
  cupertino_icons: ^1.0.8

  # --- LIBRERÍAS ACTUALIZADAS (FIX ERROR) ---
  
  # Firebase (Versiones estables más recientes)
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0

  # Diseño y Tipografía
  google_fonts: ^6.2.1

  # Utilidades
  # ACTUALIZADO A v8.0.0 PARA CORREGIR EL ERROR DE ANDROID
  file_picker: ^8.0.0  
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true